import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BookingForm from '../components/bookingform/BookingForm';
import HeroSection from '../components/herosection/HeroSection';
import WhatIsSection from '../components/whatissection/WhatIsSection';
import React, { useState, useEffect } from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='home'>
        <div className='home__container'>
          <HeroSection />
          <WhatIsSection />
          <BookingForm />
        </div>
      </main>
    </div>
  );
}
